[package]
name = "jungo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jungo"
path = "src/main.rs"

[[bin]]
name = "run_stats"
path = "src/bin/run_stats.rs"

[[bin]]
name = "test_minimax"
path = "src/bin/test_minimax.rs"

[[bin]]
name = "test_mc"
path = "src/bin/test_mc.rs"

[[bin]]
name = "test_mcts"
path = "src/bin/test_mcts.rs"

[dependencies]
rand = "0.8"
